server {
    listen 80;

    location /static/ {
        alias /app/shared/static/;
    }

    location /media/ {
        alias /app/shared/media/;
    }

    location /auth/ {
        proxy_pass http://127.0.0.1:8001/;
        proxy_set_header Host $host;
    }

    location /logout/ {
        proxy_pass http://127.0.0.1:8001/logout/;
        proxy_set_header Host $host;
    }

    location /catalog/ {
        proxy_pass http://127.0.0.1:8002/;
        proxy_set_header Host $host;
    }

    location /orders/ {
        proxy_pass http://127.0.0.1:8003/;
        proxy_set_header Host $host;
    }

    location /telegram/ {
        proxy_pass http://127.0.0.1:8004/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://127.0.0.1:8002/;
        proxy_set_header Host $host;
    }
}