server {
    listen 80;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    location /auth/ {
        proxy_pass http://127.0.0.1:8001/;
    }

    location /catalog/ {
        proxy_pass http://127.0.0.1:8002/;
    }

    location /orders/ {
        proxy_pass http://127.0.0.1:8003/;
    }

    location /telegram/ {
        proxy_pass http://127.0.0.1:8004/;
    }

    location / {
        proxy_pass http://127.0.0.1:8002/;
    }
}