server {
    listen 80 default_server;

    location /static/ {
        alias /static/;
    }

    location /media/ {
        alias /media/;
    }

    location /auth/ {
        proxy_pass http://auth-service:8001/;
        proxy_set_header Host $host;
    }

    location /logout/ {
        proxy_pass http://auth-service:8001/logout/;
        proxy_set_header Host $host;
    }

    location /catalog/ {
        proxy_pass http://catalog-service:8002/;
        proxy_set_header Host $host;
    }

    location /orders/ {
        proxy_pass http://order-service:8003/;
        proxy_set_header Host $host;
    }

    location /telegram/ {
        proxy_pass http://telegram-service:8004/;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://catalog-service:8002/;
        proxy_set_header Host $host;
    }
}