                [supervisord]
nodaemon=true
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true

[program:auth]
command=gunicorn --bind 0.0.0.0:8001 auth_app.wsgi:application
directory=/app/auth-service
autostart=true
autorestart=true

[program:catalog]
command=gunicorn --bind 0.0.0.0:8002 catalog_app.wsgi:application
directory=/app/catalog-service
autostart=true
autorestart=true

[program:order]
command=gunicorn --bind 0.0.0.0:8003 order_app.wsgi:application
directory=/app/order-service
autostart=true
autorestart=true

[program:telegram]
command=gunicorn --bind 0.0.0.0:8004 telegram_app.wsgi:application
directory=/app/telegram-service
autostart=true
autorestart=true